development:
  adapter: postgresql
  encoding: unicode
  database: fraudstar_development
  host: localhost
  pool: 5
  username: albert
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fraudstar_test
  pool: 5
  username: albert
  password: